package magneto_01.utils;

import java.util.Random;

public class AutoGeneratedData {

    // Predefined lists for company names, cities, and street names
    private static final String[] COMPANIES = {
            "Tech Solutions", "Innovative Corp", "Green Energy Ltd", "Romanian Express", "Future Technologies"
    };

    private static final String[] STREETS = {
            "Bucuresti Street", "Revolutiei Ave", "Iasi Blvd", "Victor Hugo Street", "Calea Dorobantilor"
    };

    private static final String[] CITIES = {
            "Bucuresti", "Cluj-Napoca", "Iasi", "Timisoara", "Constanta"
    };

    private static final String[] POSTAL_CODES = {
            "010011", "100000", "200000", "300000", "400000"
    };

    // Static state and country values as per the requirements
    private static final String STATE = "Bucuresti";
    private static final String COUNTRY = "Romania";

    // Function to generate a random phone number in Romania with Vodafone prefix
    private static String generatePhoneNumber() {
        Random rand = new Random();
        int number = rand.nextInt(100000000); // Generate a random 8-digit number
        return "+407" + (rand.nextInt(10) + 5) + String.format("%07d", number); //
    }

    // Class to hold all generated data for easy use and assertion
    public static class ShippingData {
        private String company;
        private String streetAddress1;
        private String streetAddress2;
        private String streetAddress3;
        private String city;
        private String state;
        private String zipCode;
        private String country;
        private String phoneNumber;

        // Constructor
        public ShippingData(String company, String streetAddress1, String streetAddress2,
                            String streetAddress3, String city, String state, String zipCode,
                            String country, String phoneNumber) {
            this.company = company;
            this.streetAddress1 = streetAddress1;
            this.streetAddress2 = streetAddress2;
            this.streetAddress3 = streetAddress3;
            this.city = city;
            this.state = state;
            this.zipCode = zipCode;
            this.country = country;
            this.phoneNumber = phoneNumber;
        }

        // Getters
        public String getCompany() {
            return company;
        }

        public String getStreetAddress1() {
            return streetAddress1;
        }

        public String getStreetAddress2() {
            return streetAddress2;
        }

        public String getStreetAddress3() {
            return streetAddress3;
        }

        public String getCity() {
            return city;
        }

        public String getState() {
            return state;
        }

        public String getZipCode() {
            return zipCode;
        }

        public String getCountry() {
            return country;
        }

        public String getPhoneNumber() {
            return phoneNumber;
        }
    }

    public static ShippingData generateShippingData() {
        Random rand = new Random();

        String company = COMPANIES[rand.nextInt(COMPANIES.length)];
        String streetAddress1 = STREETS[rand.nextInt(STREETS.length)];
        String streetAddress2 = rand.nextInt(1000) + "A"; // Random house/building number
        String streetAddress3 = "Blv " + rand.nextInt(100) + 1; // Random block/street details
        String city = CITIES[rand.nextInt(CITIES.length)];
        String zipCode = POSTAL_CODES[rand.nextInt(POSTAL_CODES.length)];
        String phoneNumber = generatePhoneNumber();

        return new ShippingData(company, streetAddress1, streetAddress2, streetAddress3, city, STATE, zipCode, COUNTRY, phoneNumber);
    }

    private static AutoGeneratedData.ShippingData shippingData;

    public static void setShippingData(AutoGeneratedData.ShippingData data) {
        shippingData = data;
    }

    public static AutoGeneratedData.ShippingData getShippingData() {
        return shippingData;
    }

    public static void main(String[] args) {
        ShippingData shippingData = generateShippingData();

        // Print the generated data for visualization
        System.out.println("Company: " + shippingData.getCompany());
        System.out.println("Street Address 1: " + shippingData.getStreetAddress1());
        System.out.println("Street Address 2: " + shippingData.getStreetAddress2());
        System.out.println("Street Address 3: " + shippingData.getStreetAddress3());
        System.out.println("City: " + shippingData.getCity());
        System.out.println("State: " + shippingData.getState());
        System.out.println("ZIP/Postal Code: " + shippingData.getZipCode());
        System.out.println("Country: " + shippingData.getCountry());
        System.out.println("Phone Number: " + shippingData.getPhoneNumber());
    }
}
